### ISSUE TITLE
Push alerts notification question

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1064]
Description:

Is it so that Android reformats the push data arriving from Cloud so it requires a new Android build for example to enable sensor offline alerts?

Is it necessary to reformat the push messages? On iOS we don't do it.

**Comment by andreevdenis** [comment]
I bet iOS also require new build to support new type of alert. Based on alert type we should select message template and insert values from the push. 

The only difference that iOS inserts values from push as is and Android uses same processing as for local alerts. We can adopt same way as iOS but I don't want to duplicate code for pushes. 

@priyonto is it correct?

What is the actual problem?

**Comment by markoaamunkajo** [comment]
@andreevdenis we would probably prefer to send push message content as complete from cloud, and not make any formatting in app. Are there any limitations that come to mind?

**Comment by andreevdenis** [comment]
Localisation can be a problem in this case

**Comment by priyonto** [comment]
I think for new alert type iOS app also will need new build. @andreevdenis is almost correct on iOS. But, I want to reiterate the iOS side again just to be clear. 

Right now iOS shows the alert threshold value and unit as it is coming from cloud. But, otherwise the message is formatted from the payload data similarly as its done on Android. 

Also, yes, for cloud to send localised formatted message, its quite some work. We have to store user device language settings to the cloud to the minimum, and not sure what else we may face.

**Comment by laurijamsa** [comment]
Actually the offline push alerts already came thru on iOS just fine when Marko tested them yesterday. Note that we will need to localise alert emails anyways, and we have a separate task already created about storing app language data in the cloud.

**Comment by priyonto** [comment]
Are offline push alerts come with same payload as the real-time push alerts?

**Comment by markoaamunkajo** [comment]
@ojousima

**Comment by markoaamunkajo** [comment]
Moving to review queue, will ask in meeting if anything else is needed

**Comment by markoaamunkajo** [comment]
Closing this card
