### ISSUE TITLE
Text alignments on sensor settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1168]
Description:

Fix paddings for description text alignments on sensor settings page.
Use same left and right paddings as under More info.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/914fc748-032b-45a9-a943-25eba785a1c3)
![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/66a45fff-b9b1-4cc7-9f7b-512879dff9ba)

**Comment by andreevdenis** [comment]
Paddings on this screen were mostly 12dp but in some cases 8dp or 16 dp. Unified everything to 16dp. We need to select bigger padding since sometimes it applies to UI elements like switches or buttons and placing them to the edge of the screen is not a good idea (especially for users with big fingers).

Keep in mind that images and icons have different sizes and empty areas inside. So even if image is aligned it might look like it's not. 

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/24788772/fae1b408-f59f-49da-8794-b318be95ecf9)

**Comment by markoaamunkajo** [comment]
Looks great for me. Moving to done.
