### ISSUE TITLE
Background scanning interval setting changing on it's own

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1299]
Description:

Seems that now there is an issue when background scanning interval is changed and phone is restarted, when user comes back he might see wrong interval in notification or in app settings or both.

**Comment by markoaamunkajo** [comment]
This issue doesn't appear when user is not signed in.

- User set 5 min interval without signing in, then signed in and interval now 1 min
- User then set 8 min interval and restarted phone right after setting it and minimising app - App showed briefly 1 min before actually showing 8 minutes interval.
- Changed to 5 min, minimised and restarted phone, then went to notifications immediately after phone restart - notification showed 5 min but app setting shows 7 min.
- Changed to 4 min, minimised and restarted phone after a while, notification shows 4 min, app shows 4 min
- Changed to 8 min, minimised and restarted phone right away, went to notifications immediately - notification shows 8 min, app shows 7 min

There seems to be a  possible cloud sync bug that gives wrong (previous) value to set interval in app.

**Comment by andreevdenis** [comment]
Absolutely no need to restart phone for this issue

**Comment by andreevdenis** [comment]
The issue applies to all kinds of user settings stored in the cloud.

When a user quickly changes the interval for background settings or switches from on to off and then on again, the app creates a settings update request that includes the timestamp of the change. Since the timestamp only includes seconds and not milliseconds, it’s possible to send 2-3 requests with the same timestamp. The cloud accepts the first request and returns an ER_CONFLICT for the subsequent changes. The setting is saved locally, but the cloud has a different value, and with the next sync, the user will receive the wrong value.

For example, when a user changes the interval from 9 minutes to 12 minutes, the app will create several requests:

{"name":"BACKGROUND_SCAN_INTERVAL","timestamp":1723464767,"value":"600"} - 10 minutes
{"name":"BACKGROUND_SCAN_INTERVAL","timestamp":1723464767,"value":"660"} - 11 minutes
{"name":"BACKGROUND_SCAN_INTERVAL","timestamp":1723464767,"value":"720"} - 12 minutes
10 minutes will be accepted, and 11 and 12 will be rejected. The user sees 12 minutes in the settings, but with the next sync, it will be changed to 10 minutes.


I've added a 1-second delay to prevent the request from executing immediately, ensuring that only the last request will be sent to the cloud.

**Comment by markoaamunkajo** [comment]
This solution works for this particular case, closing card.
