### ISSUE TITLE
History view with big font size

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1334]
Description:

Add more padding so text areas will not be stuck together/overlapping, ie. reduce texts X/Y axis when overlapping.

Example: date overlapping with next date, remove next date from view to make space.

![Image](https://github.com/user-attachments/assets/6a2bfb74-4017-480a-9e3b-68deb9497c48)

**Comment by sini-maaria** [comment]
EXAMPLES

Dates are ok here:
<img width="258" alt="Screenshot 2024-10-24 at 9 37 01" src="https://github.com/user-attachments/assets/1cd631df-fc4d-428d-9d65-3e21ab843210">

Dates are too tight, add padding to the sides so that every other date will disappear:
<img width="262" alt="Screenshot 2024-10-24 at 9 37 10" src="https://github.com/user-attachments/assets/ffba26dc-f763-4132-afc3-1dba75542638">

**Comment by markoaamunkajo** [comment]
@andreevdenis In dotted dates also still very cramped. Is it possible to improve still?

![Image](https://github.com/user-attachments/assets/590110e8-5b12-4800-932d-4d5dbc02de31)

**Comment by markoaamunkajo** [comment]
QA passed
