### ISSUE TITLE
Make it possible to resend data to Network if we had no connection at the time of some changes from user (rename or remove sensor etc)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#346]

**Comment by andreevdenis** [comment]
We can do without internet connection and be sure that it will be synced to Network when internet will be availible:
- rename sensor
- change sensor background
- delete sensor (unclaim will be performed)
- update offset for sensor
- change application settings

These actions NEED internet connection at the time of perform:
 - claim sensor
 - share sensor

**Comment by DG12** [comment]
Especially delete

**Comment by markoaamunkajo** [comment]
These will not sync new settings to network in build 1.5.19
Steps: 
1. Turn internet connection off
2. Change Sensor name
3. Change Offset corrections
4. Turn internet connection on, sync with network
5. Data coming from network will overwrite new settings instead of updating to network

Special mention:
Trying to add and update background image when internet connection is off will crash app

**Comment by markoaamunkajo** [comment]
QA passed for name, offset handled on another card
