### ISSUE TITLE
Unification: Show a loading animation when something is loading

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#471]
iOS has this feature. Let's unify.

**Comment by andreevdenis** [comment]
I didn't add similar to iOS full screen loading animation because there is no ready to use solution that will effect entire app. Also I'm not sure that it's a really good user experience. Instead let's add loading animation in places where app "thinking" too much time. @markoaamunkajo please check if we have any place in app where we might want to add loading animation.

I've changed behavior on logging in. Now we wait till initial first sync with the cloud is completed and user see all his previously saved sensors right after logging in. Also if user had dashboard enabled (setting stored in cloud) we'll change to dashboard instantly after logging in.

**Comment by andreevdenis** [comment]
1.6.11

**Comment by markoaamunkajo** [comment]
I agree it's not necessary to pollute the app with unnecessary loading icons. The only experience outside of cloud signin I can think of is GATT sync but that screen would need a whole redesign. QA passed for now.
