### ISSUE TITLE
Chart does not show (clear)(sync) buttons - 1.5.48

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#511]
Difficult to reproduce. After problem occurs its difficult to get buttons back!
Watching very carefully when switching from details then back to chart the buttons appear briefly but then seem to be over rotten by graphs.

Only 2 sensors known (others removed earlier)
![chartDoesntShowButtons-2257](https://user-images.githubusercontent.com/2365961/136680445-d4a41261-12a1-4cbe-a042-aaf02e4a9380.png)

**Comment by andreevdenis** [comment]
Most likely this happens when you use this sensor in iOS app with **Keep the Connection** toggle on. While iPhone is keeping connection we can't get history from sensor.

This video illustrates this behavior: 
https://user-images.githubusercontent.com/24788772/142232630-031ce851-8e64-4fb7-bdfa-020ddcea5f9e.mp4
