### ISSUE TITLE
Make it possible to disable Bluetooth scanning

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#547]
We have received this feedback from a few Gateway users and I can feel them. Scanning Bluetooth sensors is unnecessary in some cases if you are already getting data from the cloud. So there could be an option to turn off Bluetooth scanning in the app settings. Agree? 

Once we'll decide to go for this and start implementing, please create a corresponding iOS ticket.

![Screenshot_20211206-210413_Play Console.jpg](https://user-images.githubusercontent.com/1311912/144922914-dea7ba6a-0b0f-4bc6-a819-30f9867dd3f8.jpg)

**Comment by laurijamsa** [comment]
Strings:

Cloud Mode (not Cloud mode)

Refresh nearby cloud sensors only from the cloud by ignoring their Bluetooth messages. Requires a Ruuvi Gateway router.

Pilvitila

Päivitä lähellä olevat pilveen rekisteröidyt anturit ainoastaan pilvestä ja hylkää niiden Bluetooth-viestit. Vaatii Ruuvi Gateway -reitittimen.

**Comment by markoaamunkajo** [comment]
S8, user with gateway and 2 local sensors.
User made fresh install. He has previous local sensor in cloud and it was synced to Ruuvi Station after logging in. Added new local sensor to Ruuvi Station and then added it to cloud account, then went to settings and enabled cloud mode.

Actual: it took quite a while (maybe couple of minutes) for the new sensor to understand that it should use only cloud. Is this expected behavior @andreevdenis ?

**Comment by andreevdenis** [comment]
Yeah. Claiming sensor doesn't automatically stop BT advertisments, because we should be sure that user have Gateway, so I wait till first update from the cloud.

**Comment by markoaamunkajo** [comment]
QA passed
