### ISSUE TITLE
Hide Firmware section for shared sensor in sensor settings

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#631]

**Comment by andreevdenis** [comment]
1.8.1

**Comment by markoaamunkajo** [comment]
1.8.1 I have sensors that I have synced from cloud, should fw section also be hidden if user is in cloud mode and when last data was fetched from gateway? I think it would make sense.

**Comment by andreevdenis** [comment]
Even if app is in the cloud mode it's possible that sensor is nearby and firmware update will be successful. 

@laurijamsa your thoughts?

**Comment by laurijamsa** [comment]
Yeah I agree with Denis, I think we should not hide the DFU option when data got refreshed from the cloud and when you are owner of the sensor. Benefits of doing this would be minimal but can cause problems when owner would like to update the sensors.

One thing we were discussing with Marko a couple days ago when we were testing this issue ticket is that is it currently so that the DFU option gets hidden when someone else has already claimed the sensor and you try to claim it? I didn't try to reproduce this yet, it's just something I think I noticed when testing. It would make sense to hide it yes (because only owner should be updating the sensors), but it wasn't the spec. And even if it makes sense to hide it, it would be visible before you try to claim it because only claiming request asks ownership data from the cloud. **Maybe would be good to update ownership info from the cloud when user goes to the sensor settings page and hide the claiming button instead of doing it only if you try to claim manually someone else's sensoer. This would be better user experience. **

**Comment by andreevdenis** [comment]
This wasn't intentional. I actually don't think we should enforce it that strictly. If it's a local sensor and you have phisical access to sensor you can always sign out, add sensor and update firmware. 

And we currently can't get ownershop info without claim request.

**Comment by andreevdenis** [comment]
We've decided not to hide firmware for local sensors owned by someone else.

**Comment by markoaamunkajo** [comment]
QA passed
