### ISSUE TITLE
Entered incorrect activation code got msg "token is expired" 1.1.0(285) - nuisance 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#684]
Should be "**activation code** is _incorrect_"

**Comment by laurijamsa** [comment]
I think this error message is coming from the cloud and if would like to differentiate these two cases (wrong code or expired code), some changes would be required on the cloud side. Tagging @ojousima so that he can analyse this and create needed task(s) if necessary. After that, Otso, please close this issue.

**Comment by DG12** [comment]
Notice IOS alternate confusion :^)
Issue #893

**Comment by priyonto** [comment]
I created an issue regarding this on the Ruuvi Cloud repo.

**Comment by laurijamsa** [comment]
Our current assumption is that this is a backend issue. Closing this one.
