### ISSUE TITLE
1.13.3 S22 one sensor occasionally reports 127dBm on Add Sensor page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#761]
Description:

One local sensor with firmware 3.31.1 reports it signal strength to be 127dBm every now and then when on Add Sensors page.
This only occurs on my Samsung S22 Ultra, Android 12

Tested also on S5, S8

https://user-images.githubusercontent.com/50437378/182147181-8c0ded17-58e6-4b63-a20f-34d87d039c28.mp4

**Comment by andreevdenis** [comment]
Your Samsung is just too ultra fast!

**Comment by laurijamsa** [comment]
This could be "fixed" by adding some condition "if rssi >100dBm, discard data"? RuuviTags are broadcasting at +4dBm and due to RF losses, it's basically physically not possible to receive the signals stronger than 0dBm. Phones don't necessarily show always similar numbers but I've never seen bigger than -10dBm even if RuuviTag would be a few millimeters from the BLE receive antenna of the phone.

Or we could just decide not to fix this.

**Comment by markoaamunkajo** [comment]
Not spotted on later fw versions and tested with S10+ Android OS12
The solution should be to ask users to update firmware on their tag if spotted
Closing this issue
