### ISSUE TITLE
App settings are not saved to the cloud if user closes the app before next scheduled auto sync

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#799]
I modified the settings (hPa -> Pa) and confidently after ~30sec or so closed the app and assumed that the setting got saved ok.   But after opening the web UI hours later, I noticed that the new setting never got saved to the cloud.

We've discussed this before and I still think we'll need a similar "Successfully saved" toast message after something is saved to the cloud that we already have on the web UI. These kinds of issues are annoying and they decrease trust of users when they cannot be sure if, for example, their new alert levels got saved to the cloud or not.

**Comment by andreevdenis** [comment]
I've tried to investigate this one and I only partly agree with your suggestion.

Currently app is saving user settings with the next sync so there is 
a delay (not for alarms). And this can be easily fixed. We should send to the cloud all changes right away. 

It's probably a usual thing to show "Successfully saved" for web but not for Android. We have a local storage to keep user settings and usually it's not a big deal if temperature unit wasn't synced to the cloud due to bad Internet connection. We'll automatically try to send it again without any action needed from user. Worst case scenario is that user will have to set same setting twice for Android and for web (by the way it was requred to refresh page for me to apply synced temperature unit settings in station web).

In most of the cases I would prefer to avoid showing to user these "Successfully saved" toasts. But for alerts we should think about some sort of indication if it's synced with the cloud or not. And what should user do if it's failed to sync right away?

**Comment by laurijamsa** [comment]
> Currently app is saving user settings with the next sync so there is a delay (not for alarms). And this can be easily fixed. We should send to the cloud all changes right away.

Let's do this.

About the other enhancements (indicate user if settings are saved ok to the cloud or not), let's open a separate issue and agree mutually over there a way to implement it.

**Comment by markoaamunkajo** [comment]
QA passed.
