### ISSUE TITLE
main (?) screen  add, app settings, Abot/help... in landscape overwrites text - minor-1.16.6

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station#802]
![image](https://user-images.githubusercontent.com/2365961/194685380-e3da6cee-e2ea-4f75-ad39-546a58e2da6f.png)

**Comment by laurijamsa** [comment]
We'll have updates coming for this (iOS already has those) that would make fixing this as double work. This information will be under "My Ruuvi Account" menu item like this:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1311912/194704786-85ab17d6-65f9-4ed8-ad21-10fd8348e456.png">

Closing because of this.
