### ISSUE TITLE
Check notifications for alerts with decimal limits

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#850]
Also check disable and mute buttons from notification.

**Comment by andreevdenis** [comment]
1.15.6

**Comment by markoaamunkajo** [comment]
1.15.6 @andreevdenis If we are supposed to allow same decimals to be set as in resolution then looks like setting alert will round it to "0.0" even when "0.00" was the selected resolution.

![Screenshot_20221106-213726_Ruuvi Station](https://user-images.githubusercontent.com/50437378/200177373-6ba6e774-d14e-486c-8394-a2ad068997fd.jpg)
![Screenshot_20221106-213719_Ruuvi Station](https://user-images.githubusercontent.com/50437378/200177380-e4160daa-6e22-4e58-a6b7-50846c38b0ca.jpg)

**Comment by andreevdenis** [comment]
Accuracy settings apply to displaying values only. I round alert limits to 0.1 on purpose. Because we store these values in main units (Celsius for example) we're loosing precission in other units. When you work with F for example. Try to set alarm limit as 15.5 F in station web. Because of conversion it will be saved as 15.49. This looks wierd to me. So in my opinion it's better to avoid unnecessarily precise values and use limits of 0,1 precission. Hope it makes sense.

@laurijamsa what do you think?

**Comment by laurijamsa** [comment]
I can see that currently on Android (and web) it's possible to set alert values with 2 decimal precision (for example 20,15C). But after doing it, the app shows 20,1C.

First issue is that 20,15 should be rounded to 20,2 and not 20,1.

Second issue is that even if the app shows 20,1 as the limit, currently I get emails from the cloud that say my limit is 20,15C. Confusing.

Because we store F and K alert levels in the base format (C), we also cannot always store lower precision (0,1C) values because that would lead to even bigger problems than the current one (15,5F is shown as 15,49F).

So, maybe we should store the alert levels using 0,001C precision and round Fahrenheit to 0,01F precision. Would that fix everything?

**Comment by andreevdenis** [comment]
This might work. Can we do it as part of 1.16?

**Comment by laurijamsa** [comment]
Yeah I see why not because this is not a big issue.

**Comment by DG12** [comment]
Maybe milestone 1.150284 and 1.169034. :-)

See related issue with webui  # 216

### Inanity:
Floating point Bad. 
### irrefutable:
1) The world is round.

2) This is really a fixed point system.  In order to be virheetöntäll values for temp and hum, air-pressure  and battery should be in hundredths (or even tenths). Values for acceleration in mG.  Similar issue with charting axises.
Just because there is a decimal in it does not make it floating point.

Only thing worse (a project running under a system I was admin for (for over 10 years ) is keeping money in floating point.
Sorry I just had to vent. I guess it's too lat for that now.

**Comment by markoaamunkajo** [comment]
QA passed
