### ISSUE TITLE
New default background for new added sensors

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#875]
Description:

Must be completed together with issue:
#854 

We will remove the user selectable default background images with an empty placeholder.

1. Old sensors that used the old default background images will remain untouched, selected background image will be shown.
2. When user adds a new sensor to app it will show the new empty placeholder image in new dashboard view, in sensor card view and in sensor settings background image area.
3. If user shares this sensor to cloud we will tell cloud that there is no assigned background image.

<img width="325" alt="Screenshot 2022-11-25 at 9 09 08" src="https://user-images.githubusercontent.com/50437378/203886133-9dafc7fb-ce35-48e1-839e-34085a88be20.png">
<img width="330" alt="Screenshot 2022-11-25 at 9 08 56" src="https://user-images.githubusercontent.com/50437378/203886139-1a6b308c-c845-4a17-ad43-2ee1cbd38061.png">

**Comment by sini-maaria** [comment]
@laurijamsa will provide more specs.

<img width="754" alt="Screenshot 2022-11-25 at 9 15 51" src="https://user-images.githubusercontent.com/19531763/203923034-9f9f55bb-bf89-43a2-b855-5a929f6c64c5.png">

**Comment by laurijamsa** [comment]
Ok, so. I had a meeting with S-M and we concluded that:

- Let's replace the current dropup change background menu with a new view (view the previous comment) 
- Old users should be able to retain their default backgrounds and they should be stored to the cloud so that they would be visible also on the web ui and to be synchronised to another phones if signed in using same account. This will waste some storage in the cloud, but it'll simplify other things and users won't lose their background images.
- We'll have a new big selection of ready-made user-selectable backgrounds. There are two kinds of backgrounds: "random mood backgrounds that are applied for new sensors" and "cool photos of different measuring environments". All these will be stored in the cloud after applied manually or automatically on a sensor.
- The old school photos the app currently has will be also available on the default image selection

I may have missed something, but let's discuss and see.
