### ISSUE TITLE
1.16.1 Error about allowing notification but notifications are enabled

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#877]
Description:

The application is showing me system popup that I need to allow notifications but they are enabled and allowed everywhere in system settings.

![Screenshot_20221127-113429_Ruuvi Station](https://user-images.githubusercontent.com/50437378/204119544-f741f923-c1c8-4eeb-86e9-0cd1396bd666.jpg)
![Screenshot_20221127-113554_Settings](https://user-images.githubusercontent.com/50437378/204119533-6cd8cf98-4bfd-4d9f-82b0-5b4edbaaf526.jpg)
![Screenshot_20221127-113455_Settings](https://user-images.githubusercontent.com/50437378/204119542-e131b39a-7d72-48f3-b78b-64d9964590c5.jpg)

**Comment by andreevdenis** [comment]
Fix for this includes notification check for new dashboard. I've rewritten code there so full check is needed. Since we have some complicated logic for different Android versions and user settings here is a memo for @markoaamunkajo:

Android version 6 - 10: 

- Request for location permission
- If not in cloud mode then request to enable Bluetooth and Location service

Android version 11:

Same as for Android 6-10 and additionally ask for Bluetooth background permission if background scan is enabled.

Android version 12+:

 - Request for Nearby devices permission
 - If not in cloud mode then request to enable Bluetooth and Location service
 
Android 13+:

Same as for Android 12 and addditionally
Ask for Notification permission if background scan is enabled or any active alarm exists.

**Comment by markoaamunkajo** [comment]
QA passed
